version: '2'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        links:
            - redis
        environment:
            REDIS_HOST: redis
    redis:
        image: redis